name: release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    uses: betabitplus/ternforge-infra-ci/.github/workflows/release.yml@1929a6b39cc3e006b71deae36dee17df95d50883 # v1.2.0
    with:
      app-client-id: ${{ vars.TERNFORGE_RELEASE_CLIENT_ID }}
      repository: ${{ github.event.repository.name }}
      release-type: simple
      synchronize-python-lock: false
